"""followers

Revision ID: 83584f2bd37d
Revises: 1311f0e66f8b
Create Date: 2023-05-08 16:07:39.242940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83584f2bd37d'
down_revision = '1311f0e66f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
