"""users table

Revision ID: 8fbfe79c8590
Revises: e2b2d1598032
Create Date: 2023-03-20 19:31:59.808042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbfe79c8590'
down_revision = 'e2b2d1598032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_hashed_password', ['hashed_password'], unique=False)

    # ### end Alembic commands ###
